---
**Data**
title: "EAG_2016"
author: "Rong"
date: "Monday, September 12, 2016"
output: html_document
---

**Data**
---
```{r packages}
#load in packages
library(lme4)
library(car)
library(rmarkdown)
library(Rmisc)
library(tidyverse)
```

```{r data and summaries}
#set the working directory for wherever the files are stored
setwd("C:/Users/Rong/Box Sync/Projects/EAG Study")


#read in data, which is in wide format
EAG<- data.frame(read.csv(file="EAG_2016.csv", header=T))

#select the relevant columns
eag_hex<-EAG[,c(1:3,18,19:26)]
eag_hex[eag_hex == 0]<-NA#change zeroes to NA
tidier<-eag_hex%>%gather(Treatment, Response,-Behavior, -Individual, -Colony, -ID)#organize into long data 
tidier<-tidier%>%separate(Treatment, into=c("Pheromone", "Dose", "Control"), sep="_")%>%select(-Control)##separating treatment into multiple columns

#change 
tidier$Pheromone<-factor(tidier$Pheromone)

##renaming the dosages
tidier[which(tidier$Dose=="100ng"),]$Dose<-0.1
tidier[which(tidier$Dose=="1ug"),]$Dose<-1
tidier[which(tidier$Dose=="10ug"),]$Dose<-10
tidier[which(tidier$Dose=="100ug"),]$Dose<-100
tidier$Dose<-as.numeric(tidier$Dose)#ensuring they're numbers
tidier.numeric<-tidier
tidier$Dose<-factor(tidier$Dose, levels = c("0.1", "1", "10", "100"))

              
                    
#partition BP and Ocimene 
BP_tidier<-tidier%>%filter(Pheromone=="BP")
OCI_tidier<-tidier%>%filter(Pheromone=="Oci")

#partition nurse and forager
forage<-tidier%>%filter(Behavior=="Forager")
nurse<-tidier%>%filter(Behavior=="Nurse")

###binary regression data
##For binomial regression, set threshold to be 1
thresh=1
tidier.numeric%>%filter(Response>=thresh)->tidier.bin.up
tidier.numeric%>%filter(Response<thresh)->tidier.bin.down
tidier.bin.up$Response<-1
tidier.bin.down$Response<-0

tidy.binary<-rbind(tidier.bin.up, tidier.bin.down)
tidy.binary$Response<-factor(tidy.binary$Response)

```

```{r}

library(MBESS)
library(pwr)
library(rms)


###testing whether hexane controls before and after are significantly different.
EAG$Hexane
t.test(EAG$Hexane, EAG$Hexane.1)
wilcox.test(EAG$Hexane, EAG$Hexane.1)




#Mean and SD before
mean(EAG$Hexane, na.rm=T)
sd(EAG$Hexane, na.rm=T)
length(EAG$Hexane)
#n=58, mean = 64.83704, sd=39.86714


#Mean and SD after
mean(EAG$Hexane.1, na.rm=T)
sd(EAG$Hexane.1, na.rm=T)
length(EAG$Hexane.1)
#n=58, mean = 63.17857, sd=37.47801

#Effect size

#effectsize=(Group1mean - Group2mean)/standard deviation pooled
effectsize=(mean(EAG$Hexane, na.rm=T)-mean(EAG$Hexane.1, na.rm=T))/sd(c(EAG$Hexane.1,EAG$Hexane), na.rm=T)

#effect size of average difference
mean(EAG$Hexane-EAG$Hexane.1,na.rm=T)/sd(c(EAG$Hexane.1,EAG$Hexane), na.rm=T)
##effect size is 0.04 or 0.06

#Power Analysis for Reviewer 1
#modeled after https://stat.ethz.ch/pipermail/r-help/2011-September/290028.html
pval <- replicate(1000, wilcox.test(rnorm(54,64.83704,39.86714), rnorm(54,63.17857,37.47801))$p.value)
summary(pval)
sum(pval < .05)
 

#power analysis at small (d=0.2) and medium effect sizes (d=0.5)
pwr.t.test(n=60,d=.50,sig.level=0.05, type="paired") #97% power for medium effect
pwr.t.test(d=.50,sig.level=0.05,power = 0.8) #33% power for small effect


```


**Anovas**
---------------------------------
```{r full model}
#full model
new_model0<-lmer(Response~Behavior*Pheromone*Dose+(1|ID)+(1|Colony),tidier)

#model reduction
new_model0<-update(new_model0,.~.-Behavior:Pheromone:Dose)
new_model0<-update(new_model0,.~.-Behavior:Pheromone)
new_model0<-update(new_model0,.~.-Behavior:Dose)

#Run the anova after each update to see what changed
Anova(new_model0, type="III",test.statistic = "F")


```

```{r testing normality of residuals}
##mod.screen
resid.screen<-resid(new_model0)
plot(density(resid(new_model0)))

shapiro.test(resid(new_model0))

qqnorm(resid(new_model0))
qqline(resid(new_model0))

leveneTest(Response~Behavior*Pheromone*Dose,data=tidier)

```

```{r testing homogeneity of variances}

leveneTest(Response~Behavior, data=tidier)
leveneTest(Response~Pheromone, data=tidier)
leveneTest(Response~factor(Dose), data=tidier)
```


```{r BP vs Oci}

#BP and Oci alone
model1<-lmer(Response~Behavior*Dose+
               (1|ID)+(1|Colony), BP_tidier)
model1<-update(model1, .~.-Behavior:Dose)


model2<-lmer(Response~Behavior*Dose+(1|ID)+(1|Colony), OCI_tidier)
model2<-update(model2, .~.-Behavior:Dose)

Anova(model1,type="III",test.statistic = "F")
Anova(model2,type="III",test.statistic = "F")
```

```{r Nurse v Forager}
#Nurse and Forager alone

model3<-lmer(Response~Pheromone*Dose+
               (1|ID)+(1|Colony), nurse)
model4<-lmer(Response~Pheromone*Dose+
               (1|ID)+(1|Colony), forage)

Anova(model3,type="III")
Anova(model4,type="III")

#model reduction of full model


```

```{r non-parametric two way anova alternative}
#This can be used as an alternative to 2-way anova
#rank all of the values in both response and explanatory variables
#https://www.youtube.com/watch?v=N729aMGIUOk

# Scheirer-Ray-Hare test in R
##2-way analogue to kruskal wallis test

rank_response<-rank(tidier$Response)
rank_pheromone<-rank(tidier$Pheromone)
rank_behavior<-rank(tidier$Behavior)

#
aov.results<- aov(rank_response~rank_pheromone+rank_behavior+rank_pheromone:rank_behavior)
summary(aov.results)
Df<-anova(aov.results)[, "Df"]
SS<-anova(aov.results)[,"Sum Sq"]
Sum_SS=sum(SS)
Sum_Df<-sum(Df)
MS=Sum_SS/Sum_Df

##Calculate the H value
H_Pheromone=SS[1]/MS
H_Behavior=SS[2]/MS
H_interact_PD=SS[3]/MS

#convert in to a probability
1-pchisq(H_Pheromone, Df[1])
1-pchisq(H_Behavior, Df[2])
1-pchisq(H_interact_PD, Df[3])
```

```{r t tests and wilocoxon}
##Does Pheromone affect responses
wilcox.test(Response ~Pheromone, data=tidier, paired=F)
# W = 21021, p-value = 0.007412

ggplot(data=tidier, aes(x=Pheromone, y=Response))+geom_bar(stat = "identity")

#does pheromone affect responses in nurses or and foragers
wilcox.test(Response ~Pheromone, data=tidier[tidier$Behavior=="Nurse",], paired=F)

wilcox.test(Response ~Pheromone, data=tidier[tidier$Behavior=="Forager",], paired=F)

#nurses vs foragers
wilcox.test(Response ~Behavior, data=tidier, paired=F)
# W = 20027, p-value = 0.0006425
ggplot(data=tidier, aes(x=Behavior, y=Response))+
  geom_bar(stat = "identity") #visualize

#BP @ 0.1
wilcox.test(Response ~Behavior, data=BP_tidier,subset = Dose %in% c(0.1), paired=F)

#BP@1
wilcox.test(Response ~Behavior, data=BP_tidier,subset = Dose %in% c(1), paired=F)

#BP@10
wilcox.test(Response ~Behavior, data=BP_tidier,subset = Dose %in% c(10), paired=F)

#BP@100
wilcox.test(Response ~Behavior, data=BP_tidier,subset = Dose %in% c(100), paired=F)



#OCI@0.1
wilcox.test(Response ~Behavior, data=OCI_tidier,subset = Dose %in% c(0.1), paired=F)

#OCI@1
wilcox.test(Response ~Behavior, data=OCI_tidier,subset = Dose %in% c(1), paired=F)


#OCI@10
wilcox.test(Response ~Behavior, data=OCI_tidier,subset = Dose %in% c(10), paired=F)

#OCI@100
wilcox.test(Response ~Behavior, data=OCI_tidier,subset = Dose %in% c(100), paired=F)


# subset= Behavior %in% c("Oci","BP")

####Ocimene####
#change do to 100ng, 1 ug, 10 ug, 100ug
##10ug
nO<-c()
fO<-c()
do=levels(tidier$Dose)
for (n in do) {
oci10ug<-OCI_tidier%>%filter(Dose==n, Response!= F )
oci10ug%>%filter(Behavior=="Nurse")%>%select(Response)->nO
oci10ug%>%filter(Behavior=="Forager")%>%select(Response)->fO
print(t.test(nO, fO))

}
##Only significant for highest 100ug conc
##  1ng         t = 1.1357, df = 44.668, p-value = 0.2621
##  1ug         t = 1.6923, df = 50.266, p-value = 0.09678
##  10ug        t = 0.72588, df = 54.95, p-value = 0.471
##  100ug        t = 2.0398, df = 47, p-value = 0.04701

####BP####
#change do to 100ng, 1 ug, 10 ug, 100ug
##10ug

#cycle through all the conc for do

for (n in do) {
BP10ug<-BP_tidier%>%filter(Dose==n, Response!= F )
BP10ug%>%filter(Behavior=="Nurse")%>%select(Response)->nO
BP10ug%>%filter(Behavior=="Forager")%>%select(Response)->fO
print(t.test(nO, fO))
}
##Only significant for 10 ug conc
##  1ng         tt = 0.94036, df = 52.738, p-value = 0.3513
##  1ug         t = 0.94036, df = 52.738, p-value = 0.3513
##  10ug        t = 2.5119, df = 54.345, p-value = 0.01501
##  100ug        t = 1.4833, df = 46.734, p-value = 0.1447
```





```{r binary regression}


###separating by Pheromone only
tidy.binary%>%filter(Pheromone=="BP")->BP.binary

tidy.binary%>%filter(Pheromone=="Oci")->OCI.binary

###separating by both pheromone and behavior
tidy.binary%>%filter(Pheromone=="BP",
                     Behavior=="Nurse")->BP.Nurse.binary

tidy.binary%>%filter(Pheromone=="BP", 
                     Behavior=="Forager")->BP.Forager.binary
tidy.binary%>%filter(Pheromone=="Oci", 
                     Behavior=="Nurse")->Oci.Nurse.binary
tidy.binary%>%filter(Pheromone=="Oci", 
                    Behavior=="Forager")->Oci.Forager.binary

##full model
b.mod<- glm(Response~Dose+Behavior+Pheromone,family=binomial(link='logit'),data=tidy.binary)

##model reduction
b.mod<-update(b.mod,.~.-Dose:Behavior:Pheromone-Behavior:Pheromone-Dose:Behavior-Pheromone)
##
summary(b.mod)

library(rms)
bmod2<-lrm(formula = Response~Dose+Behavior+Pheromone, data=tidy.binary)
##since there is an interaction b/w Pheromone and Dose
#but not Pheormone alone
##we will parse datasets by Pheromone to explore further
BP.b.mod<-glm(Response~Dose+Behavior,family=binomial(link='logit'),data=BP.binary)
Oci.b.mod<-glm(Response~Dose+Behavior,family=binomial(link='logit'),data=OCI.binary)
summary(BP.b.mod)
summary(Oci.b.mod)


Oci.Nurse.binary$Response<-factor(Oci.Nurse.binary$Response)

b.mod.bp.nur <- glm(Response~Dose,family=binomial(link='logit'),data=BP.Nurse.binary)

b.mod.bp.for <- glm(Response~Dose,family=binomial(link='logit'),data=BP.Forager.binary)

b.mod.oci.nur <-glm(Response~Dose,family=binomial(link='logit'),data=Oci.Nurse.binary)

b.mod.oci.for <-glm(Response~Dose,family=binomial(link='logit'),data=Oci.Forager.binary)



summary(b.mod.oci.for)
summary(b.mod.oci.nur)
summary(b.mod.bp.for)
summary(b.mod.bp.nur)
```

```{r plotting variables}
fontsize=35
pd=position_dodge(.9)

##reds
#d7b5d8
#df65b0
#dd1c77
#980043


# blues
#bae4bc
#7bccc4
#43a2ca
#0868ac

#blue-green
#f0f9e8
#bae4bc
#7bccc4
#2b8cbe

#Greens
#edf8e9
#bae4b3
#74c476
#31a354
#006d2c

#purples
#edf8fb
#b3cde3
#8c96c6
#8856a7
blues<-c("#bae4bc","#7bccc4","#43a2ca","#0868ac")
reds<-c("#d7b5d8", "#df65b0", "#dd1c77", "#980043")
greens<-c("#bae4b3", "#74c476", "#31a354","#006d2c")
purples<-c("#edf8fb", "#b3cde3", "#8c96c6","#8856a7")
blgreen<-c("#f0f9e8", "#bae4bc", "#7bccc4", "#2b8cbe")

bluesreds<-c(rbind(blues,reds))
blgreen_purple<-c(rbind(blgreen, purples))
greenblues<-c(rbind(greens, blues))
twocolor_BR<-c("#2c7eb8", "#a7265f")

tidy.binary<-rbind(tidier.bin.up, tidier.bin.down)
sums.binary<-tidy.binary%>%group_by(Behavior,Pheromone,Dose)%>%summarize(Probability=sum(Response)/n(), se=sd(Response)/sqrt(n()))
all.binary<-merge(tidy.binary, sums.binary, by="Dose")
all.binary$Dose<-factor(all.binary$Dose,levels = c(0.1,1,10,100))
Oci.Nurse.binary$Dose<-factor(Oci.Nurse.binary$Dose,levels = c(0.1,1,10,100))
BP.Nurse.binary$Response<-factor(BP.Nurse.binary$Response, levels=c("0","1"))


```


**Figures**
---

```{r figures}
####FIG 1A######
eag_logistic_bluered<-ggplot(data=sums.binary,aes(x=Dose, col=Behavior, linetype=Behavior), alpha=0.8) +
    geom_point(aes(y=Probability,color=Behavior), size=4, 
               position = pd)+
    scale_x_log10(breaks =
                      c(0.1, 1, 10, 100),
    labels = c("0.1ug", "1ug", "10ug", "100ug"))+
    facet_grid(~Pheromone)+
    geom_smooth(data=tidy.binary,size=2,
                method="glm",
                aes(y=Response),
                formula= y~x,
                method.args = 
                  list(family = "binomial"),
                se=F)+
    ylab("Proportion responding")+
    theme_bw(fontsize)+ theme(legend.position=c(0.13,.91))+
    scale_color_manual(values = blgreen[3:4])+
    guides(color = guide_legend(keywidth = 3.1, keyheight = 1))


ggsave("eag_logistic_bluered.pdf", plot = eag_logistic_bluered,width = 14, height = 14, units = "in")


###using within subject standard error
tidier.sums<-summarySEwithin(data=tidier, measurevar = "Response", withinvars = c("Dose", "Pheromone"), betweenvars = c("Behavior"), idvar="Individual", na.rm=T)


####FIG 1B ########
##boxplot
##with blues and reds
eag_boxplot_bluered<-ggplot(tidier, aes(fill = interaction(Behavior,Dose), x=Dose, y=Response))+
    geom_boxplot(alpha=.8)+
    theme_bw(fontsize)+
    scale_fill_manual(values=rep( blgreen[c(3,4)],4), guide=F)+
    scale_x_discrete(labels=c("0.1ug", "1ug", "10ug", "100ug"))+
    facet_grid(~Pheromone)+theme(legend.position="none")

ggsave("eag_boxplot_bluered.pdf", plot = eag_boxplot_bluered,width = 14, height = 14, units = "in")




```

```{r}
boxplotlegend<-ggplot(tidier, aes(fill = Behavior, x=Dose, y=Response))+
    geom_boxplot(alpha=.8)+
    theme_bw(fontsize)+
    scale_fill_manual(values=rep( blgreen[c(3,4)],4))+
    scale_x_discrete(labels=c("0.1ug", "1ug", "10ug", "100ug"))+
    facet_grid(~Pheromone)#+theme(legend.position="none")
ggsave("boxplotlegend.pdf", plot = boxplotlegend,width = 14, height = 14, units = "in")

logisticlegend<-ggplot(data=sums.binary,aes(x=Dose, col=Behavior, linetype=Behavior), alpha=0.8) +
    geom_point(aes(y=Probability,color=Behavior), size=4, 
               position = pd)+
    scale_x_log10(breaks =
                      c(0.1, 1, 10, 100),
    labels = c("0.1ug", "1ug", "10ug", "100ug"))+
    facet_grid(~Pheromone)+
    geom_smooth(data=tidy.binary,size=2,
                method="glm",
                aes(y=Response),
                formula= y~x,
                method.args = 
                  list(family = "binomial"),
                se=F)+
    ylab("Proportion responding")+
    theme_bw(fontsize)+ theme(legend.position=c(0.13,.91))+
    scale_color_manual(values = blgreen[3:4])+
    guides(color = guide_legend(keywidth = 3.1, keyheight = 1))

ggsave("logisticlegend.pdf", plot = logisticlegend,width = 14, height = 14, units = "in")
```





